### ISSUE TITLE
7월 3일 모임

### ISSUE THREAD

**Issue by limlimlim-study** [limlimlim-study/free-coding-community#1]
**개요**
- 일정 : 7월 3일
- 시간 : 20:00 - 23:00
- 장소 : 강남 ( 모임인원에 따라 구체적인 모임공간이 결정될 예정입니다 : D )

**주제**
- 자율주제
- 개인/ 팀프로젝트 진행
- 개발서 독서
- 튜토리얼 따라하기
- 책 예제 학습

**참여방법**
댓글로 참여 의사와 모임시간에 진행할 내용을 기술해주세요.
- "참여 희망합니다. 자바스크립트 변수와 기초 문법을 연습할게요"
- "참석합니다. 프로패셔널 Nodejs 7장 파일I/O에 대해서 공부하겠습니다"
- "참석! css flex 속성을 연습해볼게요"

**Comment by ljlm0402** [comment]
참여 희망합니다. 토이 프로젝트 공부 및 코드 작성 진행하겠습니다.

**Comment by limlimlim-study** [comment]
참석합니다. http://go-tour-kr.appspot.com/ 기반 Go lang 기초 문법 학습!

**Comment by wacilpong** [comment]
참석합니다. 2시간은 도서 '오브젝트'의 챕터4를 읽고, 1시간은 리액트 개인프젝 공부해보겠습니다.

**Comment by finalsoul1** [comment]
참석합니다. _next.js_ 공부, 토이 프로젝트에 적용

**Comment by limlimlim-study** [comment]
**예약완료**
 - 장소 : 강남 카이스터디 4인실
https://beta.map.naver.com/search/%EC%B9%B4%EC%9D%B4%EC%8A%A4%ED%84%B0%EB%94%94%EC%B9%B4%ED%8E%98%20%EA%B0%95%EB%82%A8%EC%A0%90/place/1819683128?c=14139809.2851592,4509286.1331058,15,0,0,0,dh
 - 비용 : 24000 / 4 = 6000
![7_3](https://user-images.githubusercontent.com/52432327/60489623-bdf37580-9cdf-11e9-8ff1-787e0acceaf4.jpg)
