### ISSUE TITLE
7월 10일 모임

### ISSUE THREAD

**Issue by limlimlim-study** [limlimlim-study/free-coding-community#2]
**개요**
- 모임 일정 : 7월 10일 20:00-23:00
- 모집 일정 : 7월 5일 18:00
- 장소 : 강남 ( 모임인원에 따라 구체적인 모임공간이 결정될 예정입니다 : D )
- 인원 : 최대 6명

**주제**
- 자율주제
- 개인/ 팀프로젝트 진행
- 개발서 독서
- 튜토리얼 따라하기
- 책 예제 학습

**준비물**
- 개인 노트북
- 존중과 배려심

**비용**
모임 공간에 따라 상이하나 3시간 기준 6000-8000원을 크게 벗어나지 않습니다 : )

**참여방법**
댓글로 참여 의사와 모임시간에 진행할 내용을 기술해주세요.
- "참여 희망합니다. 자바스크립트 변수와 기초 문법을 연습할게요"
- "참석합니다. 저는 HTML의 기본 태그들의 의미를 공부하겠습니다"
- "참석! css flex 속성을 연습해볼게요"

**문의**
https://open.kakao.com/o/gqEyybub

**Comment by limlimlim-study** [comment]
참여 희망합니다. Go lang 기초 문법

**Comment by wacilpong** [comment]
참석! es7+ 기능들에 대한 문서를 읽고 공부해보겠습니다!

**Comment by ds2lvg** [comment]
react 기초 공부하려고 합니다.

**Comment by ljlm0402** [comment]
참석 희망합니다. YouTube 컨텐츠 제작 및 프로젝트 개발하겠습니다.

**Comment by musong0529** [comment]
참석!! react native 스터디 할려고 합니다.

**Comment by limlimlim-study** [comment]
**예약완료**
7/10 예약이 완료 되었습니다 : D
 - 장소 : 강남 노블24시스터디룸&스터디카페
https://beta.map.naver.com/search/%EA%B0%95%EB%82%A8%20%EB%85%B8%EB%B8%94%EC%8A%A4%ED%84%B0%EB%94%94/place/1261674369?c=14140288.0146914,4509083.8149602,15,0,0,0,dh 

- 비용 : 22500 / 5 = 4500
![IMG-1146](https://user-images.githubusercontent.com/52432327/60712199-6d834e80-9f51-11e9-9a77-9d0be7c826df.JPG)

- 계좌
  - 신한은행-임병철-110107489430
  - 카카오페이 
![IMG-1142](https://user-images.githubusercontent.com/52432327/60712363-d2d73f80-9f51-11e9-8cac-1bdd43892e5a.JPG)
